---
title: 'Assignment 4: LobStars in the Santa Barbara Channel'
author: "Natalie Dornan, Daphne Virlar-Knight"
date: "November 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages and read in data

```{r}
library(tidyverse)
library(kableExtra)
library(plotly)
library(vcdExtra)

lobstar_abs <- read_csv("lobster_size_abundance.csv") #data frame with lobster abundance datac

lobstar_traps <- as.data.frame(read_csv("lobster_traps.csv")) # data frame with lobster trap data


```

Natalie: Let's look at lobStar data with exploratory graphs

```{r, echo= FALSE}

## Need to decide what do do with the NR data under SIZE column: "-99999". Change to 0?

abundance_hist <- ggplot(lobstar_abs, (aes(x = SIZE))) +
  geom_histogram() +
  facet_wrap(~ SITE, scale = "free") +
  theme_classic()
  
abundance_scatter <- ggplot(lobstar_abs, (aes(x = YEAR, y = SIZE))) +
  geom_point(aes(color = "SITE")) +
  facet_wrap(~ SITE, scale = "free") +
  theme_classic()

abundance_scatter

```


Daphne: Created graphs for question 1, but not sure they're "complete enough".

1. Lobster abundance and fishing pressure
```{r}
#----------------------------------ABUNDANCE--------------------------------
#Describe trends in lobster abundance (counts) and fishing pressure (trap buoys) at the five locations from 2012 - 2017. Ignore transect information - we are only interested in evaluating abundance and pressure on the order of SITE.

#getting rid of transect data, and changing -99999 to 0
lobstar_abs_one <- lobstar_abs %>% 
  select(-SBC_LTER_TRANSECT, -LOBSTER_TRANSECT) %>% 
  mutate(SIZE = replace(SIZE, SIZE==-99999, 0)) %>% 
  group_by(YEAR, SITE) %>% 
  summarize(
    SUM = sum(COUNT)
  )

#Creating histograms of lobster abundance and fishing pressure by site. Maybe use a kable table to summarize information? Thinking out loud. 

#the next two graphs show the same data and trend. Just need to decided which we want to use.

abs_site_bar <- ggplot(lobstar_abs_one, (aes(x = YEAR, y = SUM))) +
  geom_col() +
  scale_y_continuous(expand = c(0,0))+
  xlab("Abundance")+
  ylab("Frequency")+
  facet_wrap(~ SITE, scale = "free") +
  theme_classic()

abs_site_scatter <- ggplot(lobstar_abs_one, aes(x = YEAR, y = SUM)) +
  geom_point() +
  geom_line()+
  theme_classic()+
  facet_wrap(~ SITE, scale = "free")
  
  
abs_site_scatter; abs_site_bar

#-----------------------------------TRAP PRESSURE--------------------------------

trap_pres_one <- lobstar_traps %>% 
  group_by(YEAR, SITE) %>% 
  summarize(
    SUM = sum(TRAPS)
  ) %>% 
  filter(SITE !="ABUR", SITE != "AHND to AQUE", SITE != "AHND", SITE != "GOLB")

trap_pres_scatter <- ggplot(trap_pres_one, aes(x = YEAR, y = SUM))+
  geom_point()+
  geom_line()+
  theme_classic()+
  ylab("Trap Count")+
  facet_wrap(~ SITE, scale = "free")

trap_pres_scatter

```



```{r}
trap_pres_two <- lobstar_traps %>% 
  expand.dft(freq = "TRAPS")
```

